package debugger

const instructionsNum = 256

type instruction struct {
	name       string
	ArgsFormat string
}

func (deb *Debugger) initInstructions() {
	deb.instructions[0x00] = instruction{"NOP", ""}
	deb.instructions[0x01] = instruction{"LD", "bc, n16"}
	deb.instructions[0x02] = instruction{"LD", "[bc], A"}
	deb.instructions[0x03] = instruction{"INC", "bc"}
	deb.instructions[0x04] = instruction{"INC", "b"}
	deb.instructions[0x05] = instruction{"DEC", "b"}
	deb.instructions[0x06] = instruction{"LD", "b, n8"}
	deb.instructions[0x07] = instruction{"RLCA", ""}
	deb.instructions[0x08] = instruction{"LD", "[n8], SP"}
	deb.instructions[0x09] = instruction{"ADD", "HL, BC"}
	deb.instructions[0x0A] = instruction{"LD", "A, [BC]"}
	deb.instructions[0x0B] = instruction{"DEC", "BC"}
	deb.instructions[0x0C] = instruction{"INC", "C"}
	deb.instructions[0x0D] = instruction{"DEC", "C"}
	deb.instructions[0x0E] = instruction{"LD", "C, n8"}
	deb.instructions[0x0F] = instruction{"RRCA", ""}
	deb.instructions[0x10] = instruction{"STOP", "n8"}
	deb.instructions[0x11] = instruction{"LD", "de, n16"}
	deb.instructions[0x12] = instruction{"LD", "[de], A"}
	deb.instructions[0x13] = instruction{"INC", "de"}
	deb.instructions[0x14] = instruction{"INC", "d"}
	deb.instructions[0x15] = instruction{"DEC", "d"}
	deb.instructions[0x16] = instruction{"LD", "d, n8"}
	deb.instructions[0x17] = instruction{"RLA", ""}
	deb.instructions[0x18] = instruction{"JR", "n8"}
	deb.instructions[0x19] = instruction{"ADD", "hl, de"}
	deb.instructions[0x1A] = instruction{"LD", "a, [de]"}
	deb.instructions[0x1B] = instruction{"DEC", "de"}
	deb.instructions[0x1C] = instruction{"INC", "e"}
	deb.instructions[0x1D] = instruction{"DEC", "e"}
	deb.instructions[0x1E] = instruction{"LD", "e, n8"}
	deb.instructions[0x1F] = instruction{"RRA", ""}
	deb.instructions[0x20] = instruction{"JR", "nz, n8"}
	deb.instructions[0x21] = instruction{"LD", "hl, n16"}
	deb.instructions[0x22] = instruction{"LD", "[hl+], A"}
	deb.instructions[0x23] = instruction{"INC", "hl"}
	deb.instructions[0x24] = instruction{"INC", "h"}
	deb.instructions[0x25] = instruction{"DEC", "h"}
	deb.instructions[0x26] = instruction{"LD", "h, n8"}
	deb.instructions[0x27] = instruction{"DAA", ""}
	deb.instructions[0x28] = instruction{"JR", "z, n8"}
	deb.instructions[0x29] = instruction{"ADD", "hl, hl"}
	deb.instructions[0x2A] = instruction{"LD", "a, [hl+]"}
	deb.instructions[0x2B] = instruction{"DEC", "hl"}
	deb.instructions[0x2C] = instruction{"INC", "l"}
	deb.instructions[0x2D] = instruction{"DEC", "l"}
	deb.instructions[0x2E] = instruction{"LD", "l, n8"}
	deb.instructions[0x2F] = instruction{"CPL", ""}
	deb.instructions[0x30] = instruction{"JR", "nc, n8"}
	deb.instructions[0x31] = instruction{"LD", "sp, n16"}
	deb.instructions[0x32] = instruction{"LD", "[hl-], A"}
	deb.instructions[0x33] = instruction{"INC", "sp"}
	deb.instructions[0x34] = instruction{"INC", "[hl]"}
	deb.instructions[0x35] = instruction{"DEC", "[hl]"}
	deb.instructions[0x36] = instruction{"LD", "[hl], n8"}
	deb.instructions[0x37] = instruction{"SCF", ""}
	deb.instructions[0x38] = instruction{"JR", "c, n8"}
	deb.instructions[0x39] = instruction{"ADD", "hl, sp"}
	deb.instructions[0x3A] = instruction{"LD", "a, [hl-]"}
	deb.instructions[0x3B] = instruction{"DEC", "sp"}
	deb.instructions[0x3C] = instruction{"INC", "a"}
	deb.instructions[0x3D] = instruction{"DEC", "a"}
	deb.instructions[0x3E] = instruction{"LD", "a, n8"}
	deb.instructions[0x3F] = instruction{"CCF", ""}
	deb.instructions[0x40] = instruction{"LD", "b, b"}
	deb.instructions[0x41] = instruction{"LD", "b, c"}
	deb.instructions[0x42] = instruction{"LD", "b, d"}
	deb.instructions[0x43] = instruction{"LD", "b, e"}
	deb.instructions[0x44] = instruction{"LD", "b, h"}
	deb.instructions[0x45] = instruction{"LD", "b, l"}
	deb.instructions[0x46] = instruction{"LD", "b, [hl]"}
	deb.instructions[0x47] = instruction{"LD", "b, a"}
	deb.instructions[0x48] = instruction{"LD", "c, b"}
	deb.instructions[0x49] = instruction{"LD", "c, c"}
	deb.instructions[0x4a] = instruction{"LD", "c, d"}
	deb.instructions[0x4b] = instruction{"LD", "c, e"}
	deb.instructions[0x4c] = instruction{"LD", "c, h"}
	deb.instructions[0x4d] = instruction{"LD", "c, l"}
	deb.instructions[0x4e] = instruction{"LD", "c, [hl]"}
	deb.instructions[0x4f] = instruction{"LD", "c, a"}
	deb.instructions[0x50] = instruction{"LD", "d, b"}
	deb.instructions[0x51] = instruction{"LD", "d, c"}
	deb.instructions[0x52] = instruction{"LD", "d, d"}
	deb.instructions[0x53] = instruction{"LD", "d, e"}
	deb.instructions[0x54] = instruction{"LD", "d, h"}
	deb.instructions[0x55] = instruction{"LD", "d, l"}
	deb.instructions[0x56] = instruction{"LD", "d, [hl]"}
	deb.instructions[0x57] = instruction{"LD", "d, a"}
	deb.instructions[0x58] = instruction{"LD", "e, b"}
	deb.instructions[0x59] = instruction{"LD", "e, c"}
	deb.instructions[0x5a] = instruction{"LD", "e, d"}
	deb.instructions[0x5b] = instruction{"LD", "e, e"}
	deb.instructions[0x5c] = instruction{"LD", "e, h"}
	deb.instructions[0x5d] = instruction{"LD", "e, l"}
	deb.instructions[0x5e] = instruction{"LD", "e, [hl]"}
	deb.instructions[0x5f] = instruction{"LD", "e, a"}
	deb.instructions[0x60] = instruction{"LD", "h, b"}
	deb.instructions[0x61] = instruction{"LD", "h, c"}
	deb.instructions[0x62] = instruction{"LD", "h, d"}
	deb.instructions[0x63] = instruction{"LD", "h, e"}
	deb.instructions[0x64] = instruction{"LD", "h, h"}
	deb.instructions[0x65] = instruction{"LD", "h, l"}
	deb.instructions[0x66] = instruction{"LD", "h, [hl]"}
	deb.instructions[0x67] = instruction{"LD", "h, a"}
	deb.instructions[0x68] = instruction{"LD", "l, b"}
	deb.instructions[0x69] = instruction{"LD", "l, c"}
	deb.instructions[0x6a] = instruction{"LD", "l, d"}
	deb.instructions[0x6b] = instruction{"LD", "l, e"}
	deb.instructions[0x6c] = instruction{"LD", "l, h"}
	deb.instructions[0x6d] = instruction{"LD", "l, l"}
	deb.instructions[0x6e] = instruction{"LD", "l, [hl]"}
	deb.instructions[0x6f] = instruction{"LD", "l, a"}
	deb.instructions[0x70] = instruction{"LD", "[hl], b"}
	deb.instructions[0x71] = instruction{"LD", "[hl], c"}
	deb.instructions[0x72] = instruction{"LD", "[hl], d"}
	deb.instructions[0x73] = instruction{"LD", "[hl], e"}
	deb.instructions[0x74] = instruction{"LD", "[hl], h"}
	deb.instructions[0x75] = instruction{"LD", "[hl], l"}
	deb.instructions[0x76] = instruction{"HALT", ""}
	deb.instructions[0x77] = instruction{"LD", "[hl], a"}
	deb.instructions[0x78] = instruction{"LD", "a, b"}
	deb.instructions[0x79] = instruction{"LD", "a, c"}
	deb.instructions[0x7a] = instruction{"LD", "a, d"}
	deb.instructions[0x7b] = instruction{"LD", "a, e"}
	deb.instructions[0x7c] = instruction{"LD", "a, h"}
	deb.instructions[0x7d] = instruction{"LD", "a, l"}
	deb.instructions[0x7e] = instruction{"LD", "a, [hl]"}
	deb.instructions[0x7f] = instruction{"LD", "a, a"}
	deb.instructions[0x80] = instruction{"ADD", "b"}
	deb.instructions[0x81] = instruction{"ADD", "c"}
	deb.instructions[0x82] = instruction{"ADD", "d"}
	deb.instructions[0x83] = instruction{"ADD", "e"}
	deb.instructions[0x84] = instruction{"ADD", "h"}
	deb.instructions[0x85] = instruction{"ADD", "l"}
	deb.instructions[0x86] = instruction{"ADD", "[hl]"}
	deb.instructions[0x87] = instruction{"ADD", "a"}
	deb.instructions[0x88] = instruction{"ADC", "b"}
	deb.instructions[0x89] = instruction{"ADC", "c"}
	deb.instructions[0x8a] = instruction{"ADC", "d"}
	deb.instructions[0x8b] = instruction{"ADC", "e"}
	deb.instructions[0x8c] = instruction{"ADC", "h"}
	deb.instructions[0x8d] = instruction{"ADC", "l"}
	deb.instructions[0x8e] = instruction{"ADC", "[hl]"}
	deb.instructions[0x8f] = instruction{"ADC", "a"}
	deb.instructions[0x90] = instruction{"SUB", "b"}
	deb.instructions[0x91] = instruction{"SUB", "c"}
	deb.instructions[0x92] = instruction{"SUB", "d"}
	deb.instructions[0x93] = instruction{"SUB", "e"}
	deb.instructions[0x94] = instruction{"SUB", "h"}
	deb.instructions[0x95] = instruction{"SUB", "l"}
	deb.instructions[0x96] = instruction{"SUB", "[hl]"}
	deb.instructions[0x97] = instruction{"SUB", "a"}
	deb.instructions[0x98] = instruction{"SBC", "b"}
	deb.instructions[0x99] = instruction{"SBC", "c"}
	deb.instructions[0x9a] = instruction{"SBC", "d"}
	deb.instructions[0x9b] = instruction{"SBC", "e"}
	deb.instructions[0x9c] = instruction{"SBC", "h"}
	deb.instructions[0x9d] = instruction{"SBC", "l"}
	deb.instructions[0x9e] = instruction{"SBC", "[hl]"}
	deb.instructions[0x9f] = instruction{"SBC", "a"}
	deb.instructions[0xa0] = instruction{"AND", "b"}
	deb.instructions[0xa1] = instruction{"AND", "c"}
	deb.instructions[0xa2] = instruction{"AND", "d"}
	deb.instructions[0xa3] = instruction{"AND", "e"}
	deb.instructions[0xa4] = instruction{"AND", "h"}
	deb.instructions[0xa5] = instruction{"AND", "l"}
	deb.instructions[0xa6] = instruction{"AND", "[hl]"}
	deb.instructions[0xa7] = instruction{"AND", "a"}
	deb.instructions[0xa8] = instruction{"XOR", "b"}
	deb.instructions[0xa9] = instruction{"XOR", "c"}
	deb.instructions[0xaa] = instruction{"XOR", "d"}
	deb.instructions[0xab] = instruction{"XOR", "e"}
	deb.instructions[0xac] = instruction{"XOR", "h"}
	deb.instructions[0xad] = instruction{"XOR", "l"}
	deb.instructions[0xae] = instruction{"XOR", "[hl]"}
	deb.instructions[0xaf] = instruction{"XOR", "a"}
	deb.instructions[0xb0] = instruction{"OR", "b"}
	deb.instructions[0xb1] = instruction{"OR", "c"}
	deb.instructions[0xb2] = instruction{"OR", "d"}
	deb.instructions[0xb3] = instruction{"OR", "e"}
	deb.instructions[0xb4] = instruction{"OR", "h"}
	deb.instructions[0xb5] = instruction{"OR", "l"}
	deb.instructions[0xb6] = instruction{"OR", "[hl]"}
	deb.instructions[0xb7] = instruction{"OR", "a"}
	deb.instructions[0xb8] = instruction{"CP", "b"}
	deb.instructions[0xb9] = instruction{"CP", "c"}
	deb.instructions[0xba] = instruction{"CP", "d"}
	deb.instructions[0xbb] = instruction{"CP", "e"}
	deb.instructions[0xbc] = instruction{"CP", "h"}
	deb.instructions[0xbd] = instruction{"CP", "l"}
	deb.instructions[0xbe] = instruction{"CP", "[hl]"}
	deb.instructions[0xbf] = instruction{"CP", "a"}
	deb.instructions[0xc0] = instruction{"RET", "nz"}
	deb.instructions[0xc1] = instruction{"POP", "bc"}
	deb.instructions[0xc2] = instruction{"JP", "nz, n16"}
	deb.instructions[0xc3] = instruction{"JP", "n16"}
	deb.instructions[0xc4] = instruction{"CALL", "nz, n16"}
	deb.instructions[0xc5] = instruction{"PUSH", "bc"}
	deb.instructions[0xc6] = instruction{"ADD", "n8"}
	deb.instructions[0xc7] = instruction{"RST", "$00"}
	deb.instructions[0xc8] = instruction{"RET", "z"}
	deb.instructions[0xc9] = instruction{"RET", ""}
	deb.instructions[0xca] = instruction{"JP", "z, n16"}
	deb.instructions[0xcb] = instruction{"PREFIX", ""} // TODO: add prefix processing
	deb.instructions[0xcc] = instruction{"CALL", "z, n16"}
	deb.instructions[0xcd] = instruction{"CALL", "n16"}
	deb.instructions[0xce] = instruction{"ADC", "n8"}
	deb.instructions[0xcf] = instruction{"RST", "$08"}
	deb.instructions[0xd0] = instruction{"RET", "nc"}
	deb.instructions[0xd1] = instruction{"POP", "de"}
	deb.instructions[0xd2] = instruction{"JP", "nc, n16"}
	deb.instructions[0xd4] = instruction{"CALL", "nc, n16"}
	deb.instructions[0xd5] = instruction{"PUSH", "de"}
	deb.instructions[0xd6] = instruction{"SUB", "n8"}
	deb.instructions[0xd7] = instruction{"RST", "$10"}
	deb.instructions[0xd8] = instruction{"RET", "c"}
	deb.instructions[0xd9] = instruction{"RETI", ""}
	deb.instructions[0xda] = instruction{"JP", "c, n16"}
	deb.instructions[0xdc] = instruction{"CALL", "c, n16"}
	deb.instructions[0xde] = instruction{"SBC", "n8"}
	deb.instructions[0xdf] = instruction{"RST", "$18"}
	deb.instructions[0xe0] = instruction{"LDH", "[n8], A"}
	deb.instructions[0xe1] = instruction{"POP", "hl"}
	deb.instructions[0xe2] = instruction{"LDH", "[c], a"}
	deb.instructions[0xe5] = instruction{"PUSH", "hl"}
	deb.instructions[0xe6] = instruction{"AND", "n8"}
	deb.instructions[0xe7] = instruction{"RST", "$20"}
	deb.instructions[0xe8] = instruction{"ADD", "sp, n8"}
	deb.instructions[0xe9] = instruction{"JP", "hl"}
	deb.instructions[0xea] = instruction{"LD", "[n16], a"}
	deb.instructions[0xee] = instruction{"XOR", "n8"}
	deb.instructions[0xef] = instruction{"RST", "$28"}
	deb.instructions[0xf0] = instruction{"LDH", "a, [n8]"}
	deb.instructions[0xf1] = instruction{"POP", "af"}
	deb.instructions[0xf2] = instruction{"LDH", "a, [c]"}
	deb.instructions[0xf3] = instruction{"DI", ""}
	deb.instructions[0xf5] = instruction{"PUSH", "af"}
	deb.instructions[0xf6] = instruction{"OR", "n8"}
	deb.instructions[0xf7] = instruction{"RST", "$30"}
	deb.instructions[0xf8] = instruction{"LD", "hl, sp + n8"}
	deb.instructions[0xf9] = instruction{"LD", "sp, hl"}
	deb.instructions[0xfa] = instruction{"LD", "a, [n16]"}
	deb.instructions[0xfb] = instruction{"EI", ""}
	deb.instructions[0xfe] = instruction{"CP", "n8"}
	deb.instructions[0xff] = instruction{"RST", "$38"}
}
