package debugger

const instructionsNum = 256

type instruction struct {
	name       string
	ArgsFormat string
	argsNum    int
}

func (deb *Debugger) initInstructions() {
	deb.instructions[0x00] = instruction{"NOP", "", 0}
	deb.instructions[0x01] = instruction{"LD", "bc, %02X%02X", 2}
	deb.instructions[0x02] = instruction{"LD", "[bc], A", 0}
	deb.instructions[0x03] = instruction{"INC", "bc", 0}
	deb.instructions[0x04] = instruction{"INC", "b", 0}
	deb.instructions[0x05] = instruction{"DEC", "b", 0}
	deb.instructions[0x06] = instruction{"LD", "b, %02X", 1}
	deb.instructions[0x07] = instruction{"RLCA", "", 0}
	deb.instructions[0x08] = instruction{"LD", "[%02X], SP", 1}
	deb.instructions[0x09] = instruction{"ADD", "HL, BC", 0}
	deb.instructions[0x0A] = instruction{"LD", "A, [BC]", 0}
	deb.instructions[0x0B] = instruction{"DEC", "BC", 0}
	deb.instructions[0x0C] = instruction{"INC", "C", 0}
	deb.instructions[0x0D] = instruction{"DEC", "C", 0}
	deb.instructions[0x0E] = instruction{"LD", "C, %02X", 1}
	deb.instructions[0x0F] = instruction{"RRCA", "", 0}
	deb.instructions[0x10] = instruction{"STOP", "%02X", 1}
	deb.instructions[0x11] = instruction{"LD", "de, %02X%02X", 2}
	deb.instructions[0x12] = instruction{"LD", "[de], A", 0}
	deb.instructions[0x13] = instruction{"INC", "de", 0}
	deb.instructions[0x14] = instruction{"INC", "d", 0}
	deb.instructions[0x15] = instruction{"DEC", "d", 0}
	deb.instructions[0x16] = instruction{"LD", "d, %02X", 1}
	deb.instructions[0x17] = instruction{"RLA", "", 0}
	deb.instructions[0x18] = instruction{"JR", "%02X", 1}
	deb.instructions[0x19] = instruction{"ADD", "hl, de", 0}
	deb.instructions[0x1A] = instruction{"LD", "a, [de]", 0}
	deb.instructions[0x1B] = instruction{"DEC", "de", 0}
	deb.instructions[0x1C] = instruction{"INC", "e", 0}
	deb.instructions[0x1D] = instruction{"DEC", "e", 0}
	deb.instructions[0x1E] = instruction{"LD", "e, %02X", 1}
	deb.instructions[0x1F] = instruction{"RRA", "", 0}
	deb.instructions[0x20] = instruction{"JR", "nz, %02X", 1}
	deb.instructions[0x21] = instruction{"LD", "hl, %02X%02X", 2}
	deb.instructions[0x22] = instruction{"LD", "[hl+], A", 0}
	deb.instructions[0x23] = instruction{"INC", "hl", 0}
	deb.instructions[0x24] = instruction{"INC", "h", 0}
	deb.instructions[0x25] = instruction{"DEC", "h", 0}
	deb.instructions[0x26] = instruction{"LD", "h, %02X", 1}
	deb.instructions[0x27] = instruction{"DAA", "", 0}
	deb.instructions[0x28] = instruction{"JR", "z, %02X", 1}
	deb.instructions[0x29] = instruction{"ADD", "hl, hl", 0}
	deb.instructions[0x2A] = instruction{"LD", "a, [hl+]", 0}
	deb.instructions[0x2B] = instruction{"DEC", "hl", 0}
	deb.instructions[0x2C] = instruction{"INC", "l", 0}
	deb.instructions[0x2D] = instruction{"DEC", "l", 0}
	deb.instructions[0x2E] = instruction{"LD", "l, %02X", 1}
	deb.instructions[0x2F] = instruction{"CPL", "", 0}
	deb.instructions[0x30] = instruction{"JR", "nc, %02X", 1}
	deb.instructions[0x31] = instruction{"LD", "sp, %02X%02X", 2}
	deb.instructions[0x32] = instruction{"LD", "[hl-], A", 0}
	deb.instructions[0x33] = instruction{"INC", "sp", 0}
	deb.instructions[0x34] = instruction{"INC", "[hl]", 0}
	deb.instructions[0x35] = instruction{"DEC", "[hl]", 0}
	deb.instructions[0x36] = instruction{"LD", "[hl], %02X", 1}
	deb.instructions[0x37] = instruction{"SCF", "", 0}
	deb.instructions[0x38] = instruction{"JR", "c, %02X", 1}
	deb.instructions[0x39] = instruction{"ADD", "hl, sp", 0}
	deb.instructions[0x3A] = instruction{"LD", "a, [hl-]", 0}
	deb.instructions[0x3B] = instruction{"DEC", "sp", 0}
	deb.instructions[0x3C] = instruction{"INC", "a", 0}
	deb.instructions[0x3D] = instruction{"DEC", "a", 0}
	deb.instructions[0x3E] = instruction{"LD", "a, %02X", 1}
	deb.instructions[0x3F] = instruction{"CCF", "", 0}
	deb.instructions[0x40] = instruction{"LD", "b, b", 0}
	deb.instructions[0x41] = instruction{"LD", "b, c", 0}
	deb.instructions[0x42] = instruction{"LD", "b, d", 0}
	deb.instructions[0x43] = instruction{"LD", "b, e", 0}
	deb.instructions[0x44] = instruction{"LD", "b, h", 0}
	deb.instructions[0x45] = instruction{"LD", "b, l", 0}
	deb.instructions[0x46] = instruction{"LD", "b, [hl]", 0}
	deb.instructions[0x47] = instruction{"LD", "b, a", 0}
	deb.instructions[0x48] = instruction{"LD", "c, b", 0}
	deb.instructions[0x49] = instruction{"LD", "c, c", 0}
	deb.instructions[0x4a] = instruction{"LD", "c, d", 0}
	deb.instructions[0x4b] = instruction{"LD", "c, e", 0}
	deb.instructions[0x4c] = instruction{"LD", "c, h", 0}
	deb.instructions[0x4d] = instruction{"LD", "c, l", 0}
	deb.instructions[0x4e] = instruction{"LD", "c, [hl]", 0}
	deb.instructions[0x4f] = instruction{"LD", "c, a", 0}
	deb.instructions[0x50] = instruction{"LD", "d, b", 0}
	deb.instructions[0x51] = instruction{"LD", "d, c", 0}
	deb.instructions[0x52] = instruction{"LD", "d, d", 0}
	deb.instructions[0x53] = instruction{"LD", "d, e", 0}
	deb.instructions[0x54] = instruction{"LD", "d, h", 0}
	deb.instructions[0x55] = instruction{"LD", "d, l", 0}
	deb.instructions[0x56] = instruction{"LD", "d, [hl]", 0}
	deb.instructions[0x57] = instruction{"LD", "d, a", 0}
	deb.instructions[0x58] = instruction{"LD", "e, b", 0}
	deb.instructions[0x59] = instruction{"LD", "e, c", 0}
	deb.instructions[0x5a] = instruction{"LD", "e, d", 0}
	deb.instructions[0x5b] = instruction{"LD", "e, e", 0}
	deb.instructions[0x5c] = instruction{"LD", "e, h", 0}
	deb.instructions[0x5d] = instruction{"LD", "e, l", 0}
	deb.instructions[0x5e] = instruction{"LD", "e, [hl]", 0}
	deb.instructions[0x5f] = instruction{"LD", "e, a", 0}
	deb.instructions[0x60] = instruction{"LD", "h, b", 0}
	deb.instructions[0x61] = instruction{"LD", "h, c", 0}
	deb.instructions[0x62] = instruction{"LD", "h, d", 0}
	deb.instructions[0x63] = instruction{"LD", "h, e", 0}
	deb.instructions[0x64] = instruction{"LD", "h, h", 0}
	deb.instructions[0x65] = instruction{"LD", "h, l", 0}
	deb.instructions[0x66] = instruction{"LD", "h, [hl]", 0}
	deb.instructions[0x67] = instruction{"LD", "h, a", 0}
	deb.instructions[0x68] = instruction{"LD", "l, b", 0}
	deb.instructions[0x69] = instruction{"LD", "l, c", 0}
	deb.instructions[0x6a] = instruction{"LD", "l, d", 0}
	deb.instructions[0x6b] = instruction{"LD", "l, e", 0}
	deb.instructions[0x6c] = instruction{"LD", "l, h", 0}
	deb.instructions[0x6d] = instruction{"LD", "l, l", 0}
	deb.instructions[0x6e] = instruction{"LD", "l, [hl]", 0}
	deb.instructions[0x6f] = instruction{"LD", "l, a", 0}
	deb.instructions[0x70] = instruction{"LD", "[hl], b", 0}
	deb.instructions[0x71] = instruction{"LD", "[hl], c", 0}
	deb.instructions[0x72] = instruction{"LD", "[hl], d", 0}
	deb.instructions[0x73] = instruction{"LD", "[hl], e", 0}
	deb.instructions[0x74] = instruction{"LD", "[hl], h", 0}
	deb.instructions[0x75] = instruction{"LD", "[hl], l", 0}
	deb.instructions[0x76] = instruction{"HALT", "", 0}
	deb.instructions[0x77] = instruction{"LD", "[hl], a", 0}
	deb.instructions[0x78] = instruction{"LD", "a, b", 0}
	deb.instructions[0x79] = instruction{"LD", "a, c", 0}
	deb.instructions[0x7a] = instruction{"LD", "a, d", 0}
	deb.instructions[0x7b] = instruction{"LD", "a, e", 0}
	deb.instructions[0x7c] = instruction{"LD", "a, h", 0}
	deb.instructions[0x7d] = instruction{"LD", "a, l", 0}
	deb.instructions[0x7e] = instruction{"LD", "a, [hl]", 0}
	deb.instructions[0x7f] = instruction{"LD", "a, a", 0}
	deb.instructions[0x80] = instruction{"ADD", "b", 0}
	deb.instructions[0x81] = instruction{"ADD", "c", 0}
	deb.instructions[0x82] = instruction{"ADD", "d", 0}
	deb.instructions[0x83] = instruction{"ADD", "e", 0}
	deb.instructions[0x84] = instruction{"ADD", "h", 0}
	deb.instructions[0x85] = instruction{"ADD", "l", 0}
	deb.instructions[0x86] = instruction{"ADD", "[hl]", 0}
	deb.instructions[0x87] = instruction{"ADD", "a", 0}
	deb.instructions[0x88] = instruction{"ADC", "b", 0}
	deb.instructions[0x89] = instruction{"ADC", "c", 0}
	deb.instructions[0x8a] = instruction{"ADC", "d", 0}
	deb.instructions[0x8b] = instruction{"ADC", "e", 0}
	deb.instructions[0x8c] = instruction{"ADC", "h", 0}
	deb.instructions[0x8d] = instruction{"ADC", "l", 0}
	deb.instructions[0x8e] = instruction{"ADC", "[hl]", 0}
	deb.instructions[0x8f] = instruction{"ADC", "a", 0}
	deb.instructions[0x90] = instruction{"SUB", "b", 0}
	deb.instructions[0x91] = instruction{"SUB", "c", 0}
	deb.instructions[0x92] = instruction{"SUB", "d", 0}
	deb.instructions[0x93] = instruction{"SUB", "e", 0}
	deb.instructions[0x94] = instruction{"SUB", "h", 0}
	deb.instructions[0x95] = instruction{"SUB", "l", 0}
	deb.instructions[0x96] = instruction{"SUB", "[hl]", 0}
	deb.instructions[0x97] = instruction{"SUB", "a", 0}
	deb.instructions[0x98] = instruction{"SBC", "b", 0}
	deb.instructions[0x99] = instruction{"SBC", "c", 0}
	deb.instructions[0x9a] = instruction{"SBC", "d", 0}
	deb.instructions[0x9b] = instruction{"SBC", "e", 0}
	deb.instructions[0x9c] = instruction{"SBC", "h", 0}
	deb.instructions[0x9d] = instruction{"SBC", "l", 0}
	deb.instructions[0x9e] = instruction{"SBC", "[hl]", 0}
	deb.instructions[0x9f] = instruction{"SBC", "a", 0}
	deb.instructions[0xa0] = instruction{"AND", "b", 0}
	deb.instructions[0xa1] = instruction{"AND", "c", 0}
	deb.instructions[0xa2] = instruction{"AND", "d", 0}
	deb.instructions[0xa3] = instruction{"AND", "e", 0}
	deb.instructions[0xa4] = instruction{"AND", "h", 0}
	deb.instructions[0xa5] = instruction{"AND", "l", 0}
	deb.instructions[0xa6] = instruction{"AND", "[hl]", 0}
	deb.instructions[0xa7] = instruction{"AND", "a", 0}
	deb.instructions[0xa8] = instruction{"XOR", "b", 0}
	deb.instructions[0xa9] = instruction{"XOR", "c", 0}
	deb.instructions[0xaa] = instruction{"XOR", "d", 0}
	deb.instructions[0xab] = instruction{"XOR", "e", 0}
	deb.instructions[0xac] = instruction{"XOR", "h", 0}
	deb.instructions[0xad] = instruction{"XOR", "l", 0}
	deb.instructions[0xae] = instruction{"XOR", "[hl]", 0}
	deb.instructions[0xaf] = instruction{"XOR", "a", 0}
	deb.instructions[0xb0] = instruction{"OR", "b", 0}
	deb.instructions[0xb1] = instruction{"OR", "c", 0}
	deb.instructions[0xb2] = instruction{"OR", "d", 0}
	deb.instructions[0xb3] = instruction{"OR", "e", 0}
	deb.instructions[0xb4] = instruction{"OR", "h", 0}
	deb.instructions[0xb5] = instruction{"OR", "l", 0}
	deb.instructions[0xb6] = instruction{"OR", "[hl]", 0}
	deb.instructions[0xb7] = instruction{"OR", "a", 0}
	deb.instructions[0xb8] = instruction{"CP", "b", 0}
	deb.instructions[0xb9] = instruction{"CP", "c", 0}
	deb.instructions[0xba] = instruction{"CP", "d", 0}
	deb.instructions[0xbb] = instruction{"CP", "e", 0}
	deb.instructions[0xbc] = instruction{"CP", "h", 0}
	deb.instructions[0xbd] = instruction{"CP", "l", 0}
	deb.instructions[0xbe] = instruction{"CP", "[hl]", 0}
	deb.instructions[0xbf] = instruction{"CP", "a", 0}
	deb.instructions[0xc0] = instruction{"RET", "nz", 0}
	deb.instructions[0xc1] = instruction{"POP", "bc", 0}
	deb.instructions[0xc2] = instruction{"JP", "nz, %02X%02X", 2}
	deb.instructions[0xc3] = instruction{"JP", "%02X%02X", 2}
	deb.instructions[0xc4] = instruction{"CALL", "nz, %02X%02X", 2}
	deb.instructions[0xc5] = instruction{"PUSH", "bc", 0}
	deb.instructions[0xc6] = instruction{"ADD", "%02X", 1}
	deb.instructions[0xc7] = instruction{"RST", "$00", 0}
	deb.instructions[0xc8] = instruction{"RET", "z", 0}
	deb.instructions[0xc9] = instruction{"RET", "", 0}
	deb.instructions[0xca] = instruction{"JP", "z, %02X%02X", 2}
	deb.instructions[0xcb] = instruction{"PREFIX", "", 0} // TODO: add prefix processing
	deb.instructions[0xcc] = instruction{"CALL", "z, %02X%02X", 2}
	deb.instructions[0xcd] = instruction{"CALL", "%02X%02X", 2}
	deb.instructions[0xce] = instruction{"ADC", "%02X", 1}
	deb.instructions[0xcf] = instruction{"RST", "$08", 0}
	deb.instructions[0xd0] = instruction{"RET", "nc", 0}
	deb.instructions[0xd1] = instruction{"POP", "de", 0}
	deb.instructions[0xd2] = instruction{"JP", "nc, %02X%02X", 2}
	deb.instructions[0xd4] = instruction{"CALL", "nc, %02X%02X", 2}
	deb.instructions[0xd5] = instruction{"PUSH", "de", 0}
	deb.instructions[0xd6] = instruction{"SUB", "%02X", 1}
	deb.instructions[0xd7] = instruction{"RST", "$10", 0}
	deb.instructions[0xd8] = instruction{"RET", "c", 0}
	deb.instructions[0xd9] = instruction{"RETI", "", 0}
	deb.instructions[0xda] = instruction{"JP", "c, %02X%02X", 2}
	deb.instructions[0xdc] = instruction{"CALL", "c, %02X%02X", 2}
	deb.instructions[0xde] = instruction{"SBC", "%02X", 1}
	deb.instructions[0xdf] = instruction{"RST", "$18", 0}
	deb.instructions[0xe0] = instruction{"LDH", "[%02X], A", 1}
	deb.instructions[0xe1] = instruction{"POP", "hl", 0}
	deb.instructions[0xe2] = instruction{"LDH", "[c], a", 0}
	deb.instructions[0xe5] = instruction{"PUSH", "hl", 0}
	deb.instructions[0xe6] = instruction{"AND", "%02X", 1}
	deb.instructions[0xe7] = instruction{"RST", "$20", 0}
	deb.instructions[0xe8] = instruction{"ADD", "sp, %02X", 1}
	deb.instructions[0xe9] = instruction{"JP", "hl", 0}
	deb.instructions[0xea] = instruction{"LD", "[%02X%02X], a", 2}
	deb.instructions[0xee] = instruction{"XOR", "%02X", 1}
	deb.instructions[0xef] = instruction{"RST", "$28", 0}
	deb.instructions[0xf0] = instruction{"LDH", "a, [%02X]", 1}
	deb.instructions[0xf1] = instruction{"POP", "af", 0}
	deb.instructions[0xf2] = instruction{"LDH", "a, [c]", 0}
	deb.instructions[0xf3] = instruction{"DI", "", 0}
	deb.instructions[0xf5] = instruction{"PUSH", "af", 0}
	deb.instructions[0xf6] = instruction{"OR", "%02X", 1}
	deb.instructions[0xf7] = instruction{"RST", "$30", 0}
	deb.instructions[0xf8] = instruction{"LD", "hl, sp + %02X", 1}
	deb.instructions[0xf9] = instruction{"LD", "sp, hl", 0}
	deb.instructions[0xfa] = instruction{"LD", "a, [%02X%02X]", 2}
	deb.instructions[0xfb] = instruction{"EI", "", 0}
	deb.instructions[0xfe] = instruction{"CP", "%02X", 1}
	deb.instructions[0xff] = instruction{"RST", "$38", 0}
}
