// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockiBus is a mock of iBus interface.
type MockiBus struct {
	ctrl     *gomock.Controller
	recorder *MockiBusMockRecorder
}

// MockiBusMockRecorder is the mock recorder for MockiBus.
type MockiBusMockRecorder struct {
	mock *MockiBus
}

// NewMockiBus creates a new mock instance.
func NewMockiBus(ctrl *gomock.Controller) *MockiBus {
	mock := &MockiBus{ctrl: ctrl}
	mock.recorder = &MockiBusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiBus) EXPECT() *MockiBusMockRecorder {
	return m.recorder
}

// Read mocks base method.
func (m *MockiBus) Read(addr uint16) (byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", addr)
	ret0, _ := ret[0].(byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockiBusMockRecorder) Read(addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockiBus)(nil).Read), addr)
}

// Write mocks base method.
func (m *MockiBus) Write(addr uint16, val byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", addr, val)
	ret0, _ := ret[0].(error)
	return ret0
}

// Write indicates an expected call of Write.
func (mr *MockiBusMockRecorder) Write(addr, val interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockiBus)(nil).Write), addr, val)
}
